### ISSUE TITLE
Teleporting crashes the server

### ISSUE THREAD

**Issue by EnzoPB** [benbaptist/wrapper.py#4] opened 2020-06-05 10:17 UTC
When using the /tp with coordinates, the wrapper crashes with [this error](https://hastebin.com/yenefalove.cs).

I'm using the latest dev version released on 2020-06-03, with minecraft 1.15.2 on ubuntu 20.04.

**Comment by suresttexas00** [comment] 2020-06-05 22:08
The problem is that this line https://github.com/benbaptist/wrapper.py/blob/c8520bf6d4b40d191ca79a22ab4825a331615535/wrapper/server/mcserver/console_parser.py#L17
must find a way to strip the closing (and possibly corresponding opening) brackets ( [ ] ) from the coordinates.

**Comment by benbaptist** [comment] 2020-06-06 13:38
Whoops! Good catch. Will resolve this ASAP.

**Comment by benbaptist** [comment] 2020-06-06 18:10
Fixed in the latest development code.

**Closed as completed by benbaptist** 2020-06-06 18:10 UTC
Labels: bug
